language: php
php:
    - 5.4
    - 7.1.9

addons:
    sauce_connect:
        username: "benkeen"
    jwt:
        secure: "CPw+HDifCCBOtciOW5k7fxbgcowTpyJ+eEApddekn0reTByQDdx8yxhj/NegLouuI+gE3nMtDiFbo9I0Vd5+ZGkHwHAB7IXO/CMdui5fjSVaELSfTMKOcb1yvB69NewZ4OEKKleIamJoQYlZ67xFa9Vr7BnR3GJUhIWA0jMuJSw="

services:
    - mysql

before_install:
    - echo "USE mysql;\nUPDATE user set password=PASSWORD('password') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
    - msyql -e 'CREATE DATABASE formtools;'
