language: php
php:
    - 7.1.9

before_install:
  - yarn install
  - yarn add global grunt-cli
  - travis_retry composer self-update
  - composer install --ignore-platform-reqs

install:
  - grunt prod

scripts:
  - phpunit
  - yarn test